package main

import (
	"bufio"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
)

var (
	packagePaths = make(map[string]bool)
	pkgMutex     sync.Mutex
	moduleName   string
	ignoreRules  []string
)

// 自动读取 go.mod 中的 module 名称
func getModuleName() string {
	dir, err := os.Getwd()
	if err != nil {
		return ""
	}

	for {
		modPath := filepath.Join(dir, "go.mod")
		if _, err := os.Stat(modPath); err == nil {
			file, err := os.Open(modPath)
			if err != nil {
				return ""
			}
			defer file.Close()

			scanner := bufio.NewScanner(file)
			re := regexp.MustCompile(`^module\s+(\S+)`)
			for scanner.Scan() {
				line := strings.TrimSpace(scanner.Text())
				match := re.FindStringSubmatch(line)
				if len(match) >= 2 {
					return match[1]
				}
			}
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}

	return ""
}

func main() {
	dirStr := flag.String("dir", ".", "scan directories, comma separated, e.g. -dir=./internal,./pkg,./app")
	output := flag.String("output", "auto_import.go", "output file")
	concurrency := flag.Int("concurrency", 8, "max parallel")
	ignore := flag.String("ignore", "vendor/**,.git/**,node_modules/**,testdata/**,*_test.go", "ignore patterns")
	manualModule := flag.String("module", "", "go module name (optional, auto read from go.mod)")
	flag.Parse()

	// 自动获取模块名：手动指定优先，否则自动读取
	moduleName = *manualModule
	if moduleName == "" {
		moduleName = getModuleName()
	}
	if moduleName == "" {
		fmt.Println("error: cannot find module name (not in go project or no go.mod)")
		os.Exit(1)
	}
	fmt.Printf("✅ using module: %s\n", moduleName)

	ignoreRules = strings.Split(*ignore, ",")
	sem := make(chan struct{}, *concurrency)
	var wg sync.WaitGroup

	dirs := strings.Split(*dirStr, ",")
	for _, d := range dirs {
		rootDir := strings.TrimSpace(d)
		if rootDir == "" {
			continue
		}

		absRootDir, err := filepath.Abs(rootDir)
		if err != nil {
			continue
		}

		fmt.Printf("🔍 scanning: %s\n", rootDir)

		_ = filepath.Walk(absRootDir, func(path string, f os.FileInfo, err error) error {
			if err != nil {
				return nil
			}

			if f.IsDir() {
				if isIgnored(path) {
					return filepath.SkipDir
				}
				return nil
			}

			if !strings.HasSuffix(path, ".go") {
				return nil
			}
			if isIgnored(path) {
				return nil
			}

			sem <- struct{}{}
			wg.Add(1)
			go func(filePath string, rootAbs string) {
				defer func() { <-sem }()
				defer wg.Done()

				if hasInit(filePath) {
					fileDir := filepath.Dir(filePath)
					rel, err := filepath.Rel(rootAbs, fileDir)
					if err != nil {
						return
					}
					rel = filepath.ToSlash(rel)

					baseDir := filepath.Base(rootAbs)
					var pkgPath string
					if rel == "." {
						pkgPath = moduleName + "/" + baseDir
					} else {
						pkgPath = moduleName + "/" + baseDir + "/" + rel
					}

					pkgPath = filepath.Clean(pkgPath)
					pkgPath = filepath.ToSlash(pkgPath)

					pkgMutex.Lock()
					packagePaths[pkgPath] = true
					pkgMutex.Unlock()
				}
			}(path, absRootDir)
			return nil
		})
	}

	wg.Wait()
	writeOutput(*output)
	fmt.Printf("✅ success! generated %s, found %d init packages\n", *output, len(packagePaths))
}

func hasInit(file string) bool {
	fs := token.NewFileSet()
	f, err := parser.ParseFile(fs, file, nil, 0)
	if err != nil {
		return false
	}

	for _, decl := range f.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok {
			continue
		}
		if fn.Name.Name == "init" && fn.Type.Params.NumFields() == 0 {
			return true
		}
	}
	return false
}

func isIgnored(path string) bool {
	base := filepath.Base(path)
	for _, r := range ignoreRules {
		r = strings.TrimSpace(r)
		if r == "" {
			continue
		}
		if ok, _ := filepath.Match(r, base); ok {
			return true
		}
		if strings.Contains(path, r) {
			return true
		}
	}
	return false
}

func writeOutput(out string) {
	f, _ := os.Create(out)
	defer f.Close()
	w := bufio.NewWriter(f)

	_, _ = w.WriteString("// Auto-generated by init scanner. DO NOT EDIT.\n\npackage main\n\nimport (\n")
	for pkg := range packagePaths {
		_, _ = fmt.Fprintf(w, "\t_ %q\n", pkg)
	}
	_, _ = w.WriteString(")\n")
	_ = w.Flush()
}
